#!/usr/bin/env python3
"""
报告生成模块 - 生成HTML/JSON格式的扫描报告
"""

import json
from datetime import datetime
from colorama import Fore, Style


def generate_html_report(scan_results, output_file):
    """
    生成HTML格式报告
    scan_results: 字典格式的扫描结果
    output_file: 输出文件路径
    """
    html_template = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>渗透测试报告 - IntranetPenetrationSuite</title>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            background: #ecf0f1;
            padding: 10px;
            border-radius: 5px;
        }}
        .info {{
            background: #d1ecf1;
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
        }}
        .vuln-high {{
            background: #f8d7da;
            border-left: 5px solid #dc3545;
            padding: 10px;
            margin: 10px 0;
        }}
        .vuln-medium {{
            background: #fff3cd;
            border-left: 5px solid #ffc107;
            padding: 10px;
            margin: 10px 0;
        }}
        .vuln-low {{
            background: #d1ecf1;
            border-left: 5px solid #17a2b8;
            padding: 10px;
            margin: 10px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            color: #7f8c8d;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 渗透测试报告</h1>
        <div class="info">
            <strong>生成时间:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>
            <strong>目标:</strong> {scan_results.get('target', 'N/A')}<br>
            <strong>扫描类型:</strong> {scan_results.get('scan_type', 'N/A')}
        </div>

        <h2>📊 扫描摘要</h2>
        <table>
             <tr><th>项目</th><th>数量</th></tr>
             <tr><td>开放端口</td><td>{len(scan_results.get('ports', []))}</td></tr>
             <tr><td>子域名</td><td>{len(scan_results.get('subdomains', []))}</td></tr>
             <tr><td>敏感目录</td><td>{len(scan_results.get('directories', []))}</td></tr>
             <tr><td>SQL注入</td><td>{len(scan_results.get('sql_injections', []))}</td></tr>
             <tr><td>XSS漏洞</td><td>{len(scan_results.get('xss_vulns', []))}</td></tr>
        </table>

        <h2>🖥️ 开放端口</h2>
        {generate_port_table(scan_results.get('ports', []))}

        <h2>🌐 子域名</h2>
        {generate_subdomain_table(scan_results.get('subdomains', []))}

        <h2>📁 敏感目录</h2>
        {generate_directory_table(scan_results.get('directories', []))}

        <h2>⚠️ 漏洞详情</h2>
        {generate_vuln_section(scan_results)}

        <div class="footer">
            Generated by IntranetPenetrationSuite | Author: tudougeneral
        </div>
    </div>
</body>
</html>"""

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_template)

    print(f"{Fore.GREEN}[+] 报告已生成: {output_file}{Style.RESET_ALL}")


def generate_port_table(ports):
    if not ports:
        return "<p>未扫描或未发现开放端口</p>"
    html = "<table><tr><th>端口</th><th>服务</th></tr>"
    for port in ports:
        html += f"<tr><td>{port.get('port', 'N/A')}</td><td>{port.get('service', 'unknown')}</td></tr>"
    html += "</table>"
    return html


def generate_subdomain_table(subdomains):
    if not subdomains:
        return "<p>未扫描或未发现子域名</p>"
    html = "<table><tr><th>子域名</th><th>IP</th></tr>"
    for sub in subdomains:
        html += f"<tr><td>{sub.get('domain', 'N/A')}</td><td>{sub.get('ip', 'N/A')}</td></tr>"
    html += "</table>"
    return html


def generate_directory_table(directories):
    if not directories:
        return "<p>未扫描或未发现敏感目录</p>"
    html = "<table><tr><th>目录</th><th>状态码</th></tr>"
    for d in directories:
        html += f"<tr><td>{d.get('path', 'N/A')}</td><td>{d.get('status', 'N/A')}</td></tr>"
    html += "</table>"
    return html


def generate_vuln_section(scan_results):
    html = ""

    sql_vulns = scan_results.get('sql_injections', [])
    if sql_vulns:
        for vuln in sql_vulns:
            html += f"""
            <div class="vuln-high">
                <strong>[高危] SQL注入漏洞</strong><br>
                URL: {vuln.get('url', 'N/A')}<br>
                参数: {vuln.get('parameter', 'N/A')}<br>
                Payload: {vuln.get('payload', 'N/A')}
            </div>"""

    xss_vulns = scan_results.get('xss_vulns', [])
    if xss_vulns:
        for vuln in xss_vulns:
            html += f"""
            <div class="vuln-medium">
                <strong>[中危] XSS漏洞</strong><br>
                URL: {vuln.get('url', 'N/A')}<br>
                参数: {vuln.get('parameter', 'N/A')}<br>
                Payload: {vuln.get('payload', 'N/A')}
            </div>"""

    if not sql_vulns and not xss_vulns:
        html = "<p>未发现漏洞</p>"

    return html


def generate_json_report(scan_results, output_file):
    """生成JSON格式报告"""
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(scan_results, f, indent=4, ensure_ascii=False)
    print(f"{Fore.GREEN}[+] JSON报告已生成: {output_file}{Style.RESET_ALL}")


if __name__ == '__main__':
    # 测试代码
    test_results = {
        'target': 'example.com',
        'scan_type': 'full',
        'ports': [{'port': 80, 'service': 'http'}, {'port': 443, 'service': 'https'}],
        'subdomains': [{'domain': 'www.example.com', 'ip': '1.1.1.1'}],
        'directories': [{'path': '/admin', 'status': 200}],
        'sql_injections': [],
        'xss_vulns': []
    }
    generate_html_report(test_results, 'report.html')